name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.7'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
